### ISSUE TITLE
Migrate additional NCA fields from Facilities API to CMS

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#13362]
## User Story or Problem Statement

Per #13123 , map the NCA fields from the Facilities API in Lighthouse to the CMS fields created in #13340 

## Acceptance Criteria
- [ ] I expect if a facility is recognized as missing during the migration, it should auto archive
- [x] I expect that the following fields are mapped as shown:

| Drupal field | Facilities API Selector | Notes |
| ------------ | ---------------------- | ----- |
| field_nca_classification | properties/classification | new text (plain) field |
| field_link/uri | properties/website | uri of existing Link field |
| field_link/title | facility name | title of existing Link field |
| field_timezone | properties/time_zone | new text (plain) field |
| field_mailing_address | properties/address/mailing | new Address field |
| field_address | properties/address/physical | new Address field |
| field_fax_number | properties/phone/fax | existing telephone field |
| field_phone_number | properties/phone/main | existing telephone field |
| field_office_hours | properties/hours | existing node field |

### More complex imported fields

<details><summary>field_link</summary>

```
source:
  fields:
    -
      name: field_link
      label: 'Link'

process:
  field_link/uri:
    -
      plugin: str_replace
      source: field_link
      search: 'NULL'
      replace: ''
  field_linkl/title:
    -
      plugin: str_replace
      source: <properties/name> TODO: Clarify this title
      search: 'NULL'
      replace: ''
```

</details>

<details><summary>field_mailing_address</summary>

```
source:
  fields:
    -
      name: city
      label: city
      selector: properties/address/mailing/city
    -
      name: state
      label: state
      selector: properties/address/mailing/state
    -
      name: zip
      label: zip
      selector: properties/address/mailing/zip
    -
      name: address1
      label: address1
      selector: properties/address/mailing/address_1
    -
      name: address2
      label: address2
      selector: properties/address/mailing/address_2
    -
      name: address3
      label: address3
      selector: properties/address/mailing/address_3
```

Refer to work done in 
va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
for more details

Combine API lines address_2 & address_3 into Drupal address line 2

</details>

<details><summary>field_address</summary>

```
source:
  fields:
    -
      name: city
      label: city
      selector: properties/address/physical/city
    -
      name: state
      label: state
      selector: properties/address/physical/state
    -
      name: zip
      label: zip
      selector: properties/address/physical/zip
    -
      name: address1
      label: address1
      selector: properties/address/physical/address_1
    -
      name: address2
      label: address2
      selector: properties/address/physical/address_2
    -
      name: address3
      label: address3
      selector: properties/address/physical/address_3
```

Refer to work done in 
va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
for more details

Combine API lines address_2 & address_3 into Drupal address line 2

</details>

<details><summary>field_phone_number</summary>

```
source:
  fields:
    -
      name: phone-main
      label: phone-main
      selector: properties/phone/main
process:
  field_phone_number:
    -
      plugin: str_replace
      source: phone-main
      search: Ext.
      replace: x
    -
      plugin: explode
      delimiter: x
    -
      plugin: callback
      callable: trim
    -
      plugin: concat
      delimiter: ' x'
```

Refer to work done in 
va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
for more details

</details>

<details><summary>field_office_hours</summary>

```
source:
  fields:
    -
      name: hours
      label: hours
      selector: properties/hours
process:
  field_office_hours:
    plugin: va_field_office_hours
    source: hours
```

Refer to work done in 
va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
for more details

</details>

- [ ] I expect that migration of NCA content results in the CMS fields being correctly populated.
- [ ] I expect that any Facilities product documentation related to NCA data has been updated.

## Implementation steps
See above

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [x] `Facilities`
