### ISSUE TITLE
Add timezone field to all facility content types

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13526]
## Description

- Raised in VBA design call
- In the content style guide for VA, the hours should be written with timezone 

## Acceptance Criteria
- [x] Timezone field is added to all facility content types
  - [x] NCA (covered in #13340)
  - [x] VAMC
  - [x] VBA
  - [x] Vet Center
  - [x] Vet Center Community Access Point
  - [x] Vet Center Mobile Vet Center
  - [x] Vet Center Outstation
- [x] Facility migrations from lighthouse are updated to populate the timezone field from lighthouse and added as an update 
- [x] Field choice will be defined by what we are doing for NCA #13340

NOTE:
- this does not reflect any of the front end work (to be included on separate card)

### Migration lines to add to all facilities migrations:
```
# Migration meta data.
status: true
dependencies:
  enforced:
    module:
      - tzfield
# Defines the source of the migration.
source:
  fields:
      name: time_zone
      label: time_zone
      selector: properties/time_zone
process:
  field_timezone: time_zone
destination:
  overwrite_properties:
    - field_timezone
```

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
