### ISSUE TITLE
Income Limits Automation: Implement running queries and writing to S3 for VES Data Export

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16217]
## Description

Finalize implementation of VES data exports to S3 by leveraging work on the linked ticket.

### User story

**AS AN** Income limits owner 
**I WANT** the app to be updated automatically, regularly, with new VES zipcode data
**SO THAT** Veterans receive the most up to date information in the UI.

### Engineering notes / background

S3 file locations:
https://sitewide-public-websites-income-limits-data.s3-us-gov-west-1.amazonaws.com/std_zipcode.csv
https://sitewide-public-websites-income-limits-data.s3-us-gov-west-1.amazonaws.com/std_state.csv
https://sitewide-public-websites-income-limits-data.s3-us-gov-west-1.amazonaws.com/std_incomethreshold.csv
https://sitewide-public-websites-income-limits-data.s3-us-gov-west-1.amazonaws.com/std_gmtthresholds.csv
https://sitewide-public-websites-income-limits-data.s3-us-gov-west-1.amazonaws.com/std_county.csv

<details>
<summary>Starter Github Workflow:</summary>

```yaml
name: Income Limits Data Sync
on: workflow_dispatch

env:
  NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt

jobs:
  sync:
    name: Sync Data from VES to S3
    runs-on: self-hosted

      steps:

      - name: Install Actions
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Java
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 #v3.13.0
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Test Java
        run: java -version

      - name: Setup the Node environment
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
          with:
          node-version: '18.13'

      - name: Test Node
        run: npm --version
```

</details>

### Quality / testing notes
We need to consider monitoring / alarms for failed exports.

## Acceptance criteria

- [x] Current data files are NOT overwritten
- [x] Place new files in a subfolder in the S3 bucket
- [ ] Point reviewer and confirm they look good
- [ ] Create ticket to do final cutover and formalize using the new data
