### ISSUE TITLE
Successful CI runs on main for Next Build should publish content to dev and staging.

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18047]
## Requirements

If Continuous Integration runs and completes successfully for the `main` branch of Next Build, this should result in publication of content to the dev and staging environments, so that those environments always represent the up-to-date state of Next Build.

```[tasklist]
### Acceptance criteria
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18046
- [ ] Upon successful Continuous Integration on `main`, the Content Release workflow will be triggered and publish content to dev and staging
```

## Background & implementation details

Currently Content Release is set up run upon a successful CI run on `main`, via creation of a Production Tag: 
```
on:
  repository_dispatch: # Not relevant to this ticket
    types: [content-release]
  workflow_run:
    workflows: ['Create Production Tag']
    types: [completed]
    branches: [main]
```
At time of writing, this publishes content to the production bucket. This should be modified such that it publishes to dev and to staging environments.

- We need to account for concurrency groups; right now it's relying on `input.build_type` and that will not always be a value that exists
- we want to fire the actual build via a matrix if possible so that we can build more than one environment type simultaneously.
