### ISSUE TITLE
Remove "closed" operating status from Drupal

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#20738]
## Description

The 'Closed' operating status for facilities needs to be removed from the Drupal backend. This involves updating the configuration file to ensure the 'Closed' status is no longer an option. It will also be necessary to remove the "closed" status from any facilities that currently have it (see attached .csv).

## Tasks

1. **Update Configuration**:
   - Modify the `config/sync/field.storage.node.field_operating_status_facility.yml` file to remove the 'Closed' operating status option.

### Updated Configuration File

Replace the content of `config/sync/field.storage.node.field_operating_status_facility.yml` with the following:

```yaml name=config/sync/field.storage.node.field_operating_status_facility.yml
uuid: 865cd8d7-fa61-4174-a21e-e386ab083d7e
langcode: en
status: true
dependencies:
  module:
    - node
    - options
id: node.field_operating_status_facility
field_name: field_operating_status_facility
entity_type: node
type: list_string
settings:
  allowed_values:
    -
      value: normal
      label: 'Normal services and hours'
    -
      value: limited
      label: 'Limited services and hours'
    -
      value: temporary_closure
      label: 'Temporary facility closure'
    -
      value: temporary_location
      label: 'Temporary location'
    -
      value: virtual_care
      label: 'Virtual care only'
    -
      value: coming_soon
      label: 'Coming soon'
    -
      value: notice
      label: 'Facility notice'
  allowed_values_function: ''
module: options
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
```

## Acceptance Criteria

- [x] Remove `Closed` from the allowed values for the operating status field in `config/sync/field.storage.node.field_operating_status_facility.yml`as described above.
- [x] All facilities (published, archived or draft) that are currently using closed are changed to a "Temporarily closed" operating status, based on [facility-status-export-2.csv](https://github.com/user-attachments/files/19032533/facility-status-export-2.csv)
   - [x] Change in status and details should be saved as a revision
- [x] The 'Closed' operating status is no longer available as an option in the Drupal backend.
   - [x] Check each of the facility content types 
   - [x] Check any relevant views 
   - [x] Check any relevant automated tests 

## References
- [facility-status-export-2.csv](https://github.com/user-attachments/files/19032533/facility-status-export-2.csv)
- [Current configuration file](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/config/sync/field.storage.node.field_operating_status_facility.yml)

## Additional Information

Please ensure thorough testing to verify that the 'Closed' status is completely removed and that no errors occur due to its removal.
