### ISSUE TITLE
Investigate Code Quality Tools

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#3486]
## Description

Currently on PHPCS is run as a static code analysis.  To improve the quality of our code going forward we should add other static code analysis tools that rate the "quality" of our code.

This issue is to find possible tools to use and evaluate.

## Acceptance Criteria
- [ ] One or more code quality tools are selected to implement.
- [ ] Follow up epics and issues are created to implement code quality tools

**Comment by ndouglas** [comment]
This is relevant to my interests.

I've used PHPStan before and gotten good results. [Here](https://github.com/mglaman/phpstan-drupal) is a Drupal-specific extension to PHPStan, which I've also used.

I used this as my (root directory) `phpstan.neon` file, which ignored some errors that I found irritating and baseless:

```yaml
parameters:
  excludes_analyse:
    - *Test.php
    - *TestBase.php
  level: 2
  ignoreErrors:
    - '#Plugin manager has cache backend specified but does not declare cache tags.#'
    - '#Missing cache backend declaration for performance.#'
    - '#Plugin definitions cannot be altered.#'
  reportUnmatchedIgnoredErrors: false
  bootstrap: phpstan_bootstrap.php
includes:
  - vendor/mglaman/phpstan-drupal/extension.neon
```

This is the current content of my `phpstan_bootstrap.php` file, which currently just chains the core bootstrap file but is a useful place to throw code in some situations:

```php
<?php

/**
 * @file
 * Our friend, the testing bootstrap file.
 *
 * phpcs:ignoreFile
 */

require_once 'docroot/core/tests/bootstrap.php';
```

And I used this command in my pre-commit hook to run PHPStan on changed files:

```bash
# PHPStan.
git diff --diff-filter=d --cached --name-only -z -- \
  ':(exclude)docroot/core' \
  ':(exclude)docroot/sites/default' \
  ':(exclude)docroot/modules/contrib' \
  ':(exclude)docs' \
  ':(exclude)node_modules' \
  ':(exclude)reports' \
  ':(exclude)vendor' \
  ':(exclude)*Test.php' \
  ':(exclude)*/tests/*' \
  '*.php' \
  '*.inc' \
  '*.module' \
  | xargs -0 -I % sh -c 'export my_file="$0"; ./vendor/bin/phpstan analyze "${my_file}" -n -l 2 --memory-limit=4000M --error-format=raw --no-progress -c phpstan.neon;' "%";
phpstan_exit=$?;
if [ ${phpstan_exit} -eq 0 ]; then
  echo -e "${success_icon} PHPStan passed";
else
  echo -e "${failure_icon} PHPStan failed!" 1>&2;
  exit ${phpstan_exit};
fi
```

obv running it only on changed files isn't going to catch every issue, but we could probably run it more comprehensively in Tugboat or something.  IDK.

This is more just documentation than anything else -- should enable you or someone else to get a fairly quick start on evaluating whether it fits our needs.
