### ISSUE TITLE
Uninstall Tome

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4262]
https://www.drupal.org/project/tome

## Acceptance Criteria
- [x] module is uninstalled from drupal

**Comment by indytechcook** [comment]
For some reason the update didn't remove the modules.  I found the item in the log and I didn't see the success or error messages that I expected

```
 TASK [Run 'drush updatedb'] ****************************************************
 Tuesday 09 March 2021  20:52:24 +0000 (0:00:00.033)       0:02:45.312 ********* 
 changed: [ip-10-247-32-9.us-gov-west-1.compute.internal]
 
 TASK [debug] *******************************************************************
 Tuesday 09 March 2021  20:53:18 +0000 (0:00:54.485)       0:03:39.797 ********* 
 ok: [ip-10-247-32-9.us-gov-west-1.compute.internal] => 
   drushupdatedb.stdout_lines:
   - 'The following updates are pending:'
   - ''
   - 'va_gov_db module : '
   - '  8023 -   Uninstall tome modules. '
   - ''
   - 'Do you wish to run all pending updates? (y/n): y'
   - Performing va_gov_db_update_8023                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [ok]
   - Skipping cache-clear operation due to --cache-clear=0 option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [warning]
   - Skipping cache-clear operation due to --cache-clear=0 option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [ok]
   - Finished performing updates.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [ok]
```

When I run a 2nd updb locally see them uninstalled

```
>  [notice] Update started: va_gov_db_update_8024
>  [notice] Uninstalled the following modules: tome_static, tome_base
>  [notice] Update completed: va_gov_db_update_8024
``` 

I'm going to set them to run again, perhaps it was an issue with the drush upgrade.
