### ISSUE TITLE
Set alert to "none" for existing R&S pages that do not have a value 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4384]
## Description

See [Slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1614006944000100) with @RLHecht . 

Some R&S nodes created before a certain date have a NULL value for the "Alert (single)". When editors edit one of the pages, they get an "Alert field is required" error if they edit a different field and save. 

## ACs

- [ ] "Alert (single)" is set to "None" instead of NULL for all nodes of the 7 content types tagged with "LC" as Primary Product on the Bundles tab of the Drupal Spec tool. 

## Implementation 

- [ ] Quick audit of how many nodes are affected
- [ ] decide on manual vs update script approach to updating thesenodes  

## Screenshots

![image](https://user-images.githubusercontent.com/643678/108762046-9a68e880-751d-11eb-8f11-4e7033a17138.png)

![Create_Step-by-Step___VA_gov_CMS_and_Create_FAQ_-_multiple_Q_As___VA_gov_CMS_and_Create_Media_list_-_Images___VA_gov_CMS_and_Create_Resources_and_support_Detail_Page___VA_gov_CMS_and_Create_Media_list_-_Videos___VA_gov_CMS_and_Create_Q_A___](https://user-images.githubusercontent.com/643678/108762008-91781700-751d-11eb-8470-2ba478585b33.png)

**Comment by ethanteague** [comment]
Created a view, and added all the R&S types, then made a relationship to the single alert paragraph. Filtered by `filed_alert_selection === NULL` and returned 0 results. This no longer appears to be a thing, @kevwalsh . View export for QA:
```
uuid: bb27b0b5-8a9b-45f2-aac1-e065b7f10876
langcode: en
status: true
dependencies:
  config:
    - node.type.checklist
    - node.type.faq_multiple_q_a
    - node.type.media_list_images
    - node.type.media_list_videos
    - node.type.q_a
    - node.type.step_by_step
    - node.type.support_resources_detail_page
  module:
    - node
    - options
    - paragraphs
    - user
id: blank_alert
label: 'blank alert'
module: views
description: ''
tag: ''
base_table: node_field_data
base_field: nid
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 0
    display_options:
      access:
        type: perm
        options:
          perm: 'access content'
      cache:
        type: tag
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: 50
          offset: 0
          id: 0
          total_pages: null
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          quantity: 9
      style:
        type: default
      row:
        type: fields
      fields:
        title:
          id: title
          table: node_field_data
          field: title
          settings:
            link_to_entity: true
          plugin_id: field
          relationship: none
          group_type: group
          admin_label: ''
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      filters:
        status:
          value: '1'
          table: node_field_data
          field: status
          plugin_id: boolean
          entity_type: node
          entity_field: status
          id: status
          expose:
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
          group: 1
        type:
          id: type
          table: node_field_data
          field: type
          relationship: none
          group_type: group
          admin_label: ''
          operator: in
          value:
            checklist: checklist
            faq_multiple_q_a: faq_multiple_q_a
            media_list_images: media_list_images
            media_list_videos: media_list_videos
            q_a: q_a
            support_resources_detail_page: support_resources_detail_page
            step_by_step: step_by_step
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          entity_type: node
          entity_field: type
          plugin_id: bundle
        field_alert_selection_value:
          id: field_alert_selection_value
          table: paragraph__field_alert_selection
          field: field_alert_selection_value
          relationship: field_alert_single
          group_type: group
          admin_label: ''
          operator: empty
          value:
            all: all
            NA: NA
            R: R
            NR: NR
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          reduce_duplicates: false
          plugin_id: list_field
      sorts:
        created:
          id: created
          table: node_field_data
          field: created
          order: DESC
          entity_type: node
          entity_field: created
          plugin_id: date
          relationship: none
          group_type: group
          admin_label: ''
          exposed: false
          expose:
            label: ''
          granularity: second
      title: 'blank alert'
      header:
        result:
          id: result
          table: views
          field: result
          relationship: none
          group_type: group
          admin_label: ''
          empty: false
          content: 'Displaying @start - @end of @total'
          plugin_id: result
      footer: {  }
      empty: {  }
      relationships:
        field_alert_single:
          id: field_alert_single
          table: node__field_alert_single
          field: field_alert_single
          relationship: none
          group_type: group
          admin_label: 'field_alert_single: Paragraph'
          required: true
          plugin_id: standard
      arguments: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url.query_args
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }
  block_1:
    display_plugin: block
    id: block_1
    display_title: Block
    position: 1
    display_options:
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url.query_args
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }

```
