### ISSUE TITLE
Published node count data not available in Prometheus

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5432]
**Describe the defect**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS objective (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

**Comment by olivereri** [comment]
The configuration for the scrape job we used before wasn't targeting CMS instances within the DSVA account.  This below config is a start to achieve this:

```
  - job_name: 'cms-ec2-instances-drupal-test'
    metrics_path: /metrics
    scrape_interval: 5m
    scrape_timeout: 30s
    ec2_sd_configs:
      - region: 'us-gov-west-1'
        port: 80
    relabel_configs:
      - source_labels: [__meta_ec2_tag_environment,__meta_ec2_tag_project]
        regex: '^dev;(vetsgov|vagov|dvp)$'
        action: keep
      - source_labels: [__meta_ec2_tag_Purpose]
        regex: '^(cms|cms-test)$'
        action: keep
      - source_labels: [__meta_ec2_tag_Purpose]
        target_label: purpose
      - source_labels: [__meta_ec2_tag_environment]
        target_label: env
```

Then in Grafana we can display the metrics with in a query like:
`
drupal_node_count_total{env="$environment",job="cms-ec2-instances-drupal-test",purpose="$app_name",status="published"}
`
