### ISSUE TITLE
Create long term solution for memcache container memory limit for CI and local

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#5578]
In #5491 we solved an "out of memory" memcache issue with a short term fix of extending the Tugboat Memcached container and bumping the runtime memory allocated to it from 256MB to 1024MB. We had to push a container image to Docker Hub for this and it isn't ideal that we maintain this container long term. 

## Acceptance Criteria
- [ ] Work with Tugboat to make the memory limit configurable in the config.yml
- [ ] Implement solution in comment below 
- [ ] Clean up previous docker hub image 

## Tasks
- [x] Update Lando config
- [x] Update Tugboat config
- [x] Test
- [ ] Merge
- [ ] Rebuild Tugboat base images
- [ ] Delete image from DockerHub after this PR

**Comment by ElijahLynn** [comment]
Solution here from @q0rban https://dsva.slack.com/archives/C01A35JDH88/p1623360886023100?thread_ts=1622563487.013300&cid=C01A35JDH88

```
services:
  ...
  memcache:
    image: tugboatqa/memcached:1.6
    commands:
      init:
        - sed -e 's/256/1024/' -i /etc/service/memcached/run
        - sv restart memcached
```
