### ISSUE TITLE
Create Dockerfile for EKS Onboarding Process with Ops

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#6461]
## Description
As a CMS Devops Engineer, I need to create a Dockerfile for CMS, so that I can define container image with Drupal and customizations installed for deployment on EKS.

## Acceptance Criteria

- [x] Create a Dockerfile that can generate a container image with all the necessary software and dependencies to run the content management system. Enough to get through the onboarding process.
- [x] Image is successfully built from Dockerfile.

## Implementation Details

An example of what this may look like can be found here:
https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/.tugboat/config.yml

**Comment by olivereri** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6461?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas

**Comment by ElijahLynn** [comment]
We should look at Geerling guys container images like Drupal Container.

**Comment by ElijahLynn** [comment]
Also possibly Lagoon's containers.

**Comment by ndouglas** [comment]
I'm not doing anything else this afternoon, so I figured I'd pop on and share my opinions.

- I don't think Jeff's [Dockerfile](https://github.com/geerlingguy/drupal-container/blob/master/Dockerfile) is particularly helpful.  It seems really barebones to me.

- I don't think [Lagoon's](https://github.com/uselagoon/lagoon-images/blob/main/images/nginx-drupal/Dockerfile) is either.  I've done it before, but I don't particularly like mixing Drupal with Nginx because the Drupal project assumes Apache by default and it becomes extra effort to duplicate and then maintain the functionality of `.htaccess`, `mod_rewrite`, etc within Nginx.  Lagoon might have an Apache-based image I'm missing, or there might be issues with my dismissal of Nginx in this context 🤷

**Comment by ndouglas** [comment]
I was on the subject so I thought I'd take a quick swing at this:

```Dockerfile
FROM php:7.3-apache AS cms_build

ENV GIT_OPTIONS="--branch master"
ENV CMS_REPO_ROOT="/var/www/cms"
ENV CMS_DOCROOT="$CMS_REPO_ROOT/docroot"
ENV PHP_VERSION="7.3"

# Copy Composer into container rather than installing it.
COPY --from=composer:2.1.8 /usr/bin/composer /usr/local/bin/composer

# php-extension-installer makes working with PHP modules a lot easier
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

# Install VA internal certificate.
ADD http://crl.pki.va.gov/PKI/AIA/VA/VA-Internal-S2-RCA1-v1.cer /usr/local/share/ca-certificates/
RUN openssl x509 -inform DER -in /usr/local/share/ca-certificates/VA-Internal-S2-RCA1-v1.cer -out /usr/local/share/ca-certificates/VA-Internal-S2-RCA1-v1.crt
RUN update-ca-certificates

# Use default production values.
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Inject PHP conf overrides (currently just `apc.enable=1`, need to ensure this is enabled on CLI too)
COPY my-php.ini $PHP_INI_DIR/conf.d/my-php.ini
COPY my-php-cli.ini $PHP_INI_DIR/conf.d/my-php-cli.ini

# Change docroot.
RUN sed -ri -e 's#/var/www/html#${CMS_DOCROOT}/docroot#g' \
  /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's#/var/www/#${CMS_DOCROOT}/docroot#g' \
  /etc/apache2/apache2.conf \
  /etc/apache2/conf-available/*.conf

RUN install-php-extensions \
  apcu \
  gd \
  memcache \
  opcache \
  xdebug \
  # Drush 10 requirement
  zip

# Install dependencies
RUN apt-get update \
  && apt-get install -y \
    # Git (for cloning the va.gov-cms repo)
    git \
    # unzip (for unzipping Composer zip files)
    unzip

# Change to /var/www...
WORKDIR $CMS_REPO_ROOT/..
RUN ls -lha /var/www \
  && chown -R www-data:www-data /var/www
USER www-data
WORKDIR $CMS_REPO_ROOT/..

# And check out the repository.
RUN git clone https://github.com/department-of-veterans-affairs/va.gov-cms.git cms\
  --depth 1 \
  $GIT_OPTIONS

WORKDIR $CMS_REPO_ROOT
```

IDK if it works, but it builds.  I'm out for the day, though 😃  There's a lot of room for improvement like possibly shifting to a multistage build and segregating the build/test dependencies, nuking Composer cache, etc, to get the final image size down.  Segregating build/test dependencies compromises the goal of running the same image in all environments though, arguably, so IDK.

**Comment by olivereri** [comment]
> nuking Composer cache, etc, to get the final image size down.

Yeah, this a big one!

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/b85442e2-144e-4d33-aee0-e647494166dc)

**Comment by ndouglas** [comment]
```
Belmore:va.gov-cms nathan.douglas$ du -d1 -h | sort -h
4.0K	./.composer-cache
4.0K	./hooks
8.0K	./.vscode
 12K	./.devcontainer
 12K	./.lando
 24K	./patches
 40K	./.tugboat
 56K	./simplesamlphp-config-metadata
 64K	./.web
120K	./.github
252K	./scripts
580K	./drush
784K	./product-release-notes
1.8M	./tests
2.6M	./READMES
4.5M	./bin
 11M	./config
287M	./.git
314M	./node_modules
8.5G	./.dumps
8.6G	./docroot
 18G	.
 ```
 
 Just occurred to me that I probably copied all kinds of crap into that image that shouldn't be copied.  Need a `.dockerignore`

**Comment by ndouglas** [comment]
d'oh, it copies the images, etc in too, lol

**Comment by olivereri** [comment]
Not a huge problem. To speed it up committing the image to ECR (A6 AWS Account) I'm doing it on an EC2. Goal is to try and create a simple K8s manifest that pulls in this container image and deploys it with my local ArgoCD. Then I can report back what's up with the Dockerfile after I hook a DB up to it.

**Comment by ndouglas** [comment]
Yeah, I started with the approach of pulling the CMS repo in within the container as part of the build process, but that complicated my life so I just switched to copying it in under the assumption that the Dockerfile existed in the repo.  Not positive which is the best approach in this situation.

**Comment by olivereri** [comment]
I like the latter approach because it probably jives well with how we'll might build the container with GHA.  One workflow task checks out the repo, Dockerfile and all, then we build without the complication of trying to clone the repo _in_ the container.

**Comment by olivereri** [comment]
Getting somewhere! Still missing a few pieces but I'm sure I can replicate what we do for Tugboat in K8s+ArgoCD to verify and tweak the Dockerfile.

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/d441a632-d70b-42f6-a829-0e0673e2a422)

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/a9e21a93-11a5-452e-8d45-7a4666eac8e2)

**Comment by ndouglas** [comment]
yeah, that's what it looks like when it's not able to reach the DB server.

```
$databases['default']['default'] = array(
  'driver' => 'mysql',
  'database' => getenv('CMS_MARIADB_DATABASE') ?: 'drupal8',
  'username' => getenv('CMS_MARIADB_USERNAME') ?: 'drupal8',
  'password' => getenv('CMS_MARIADB_PASSWORD') ?: 'drupal8',
  'prefix' => '',
  // 'database' is the default DB container for Lando (local).
  'host' => getenv('CMS_MARIADB_HOST') ?: 'database',
  'port' => 3306,
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
);
```

I'll play with it this morning locally and open a PR including `Dockerfile` and `.dockerignore` to see what nightmares we encounter next 😃

**Comment by ndouglas** [comment]
I forked your repo to [here](https://github.com/ndouglas/vsp-infra-cms) just so I can play with it on my cluster, set up a DB, etc.  I figure I'll toss in a CronJob, etc once I get the DB layer working.

**Comment by ndouglas** [comment]
Ideally most of it (outside the DB/Memcache stuff, which would be irrelevant) can be backported easily into EKS

**Comment by olivereri** [comment]
> yeah, that's what it looks like when it's not able to reach the DB server.

I eventually found how settings.php does an include from docroot/sites/default/settings/ which contains a bunch of other specific settings.php file.  Suppose I can create a new container that has a settings.eks.php with the values for a database service.  The DB container I was thinking create a sperate Dockerfile using MariaDB 10.5 and load up latest CMS DB like Tugboat does:

```
        - curl --remote-name https://dsva-vagov-prod-cms-backup-sanitized.s3-us-gov-west-1.amazonaws.com/database/cms-prod-db-sanitized-latest.sql.gz
        - mysql -e "DROP DATABASE IF EXISTS tugboat; CREATE DATABASE tugboat";
        - zcat cms-prod-db-sanitized-latest.sql.gz | mysql tugboat
        - rm cms-prod-db-sanitized-latest.sql.gz
```

**Comment by ndouglas** [comment]
<img width="789" alt="Screen Shot 2021-09-29 at 1 00 22 PM" src="https://user-images.githubusercontent.com/1318579/135315339-e85d51c4-ad8d-4c4d-935d-93a4c86be240.png">

The Dockerfile's at least somewhat legit at this point -- this is the same image I built this morning.  Just need to get the DB loaded and files copied to see what breaks next 😄

**Comment by ndouglas** [comment]
I'ma see if I can do that DB/file loading in an initContainer

**Comment by ndouglas** [comment]
IDK if you saw this @olivereri https://hub.docker.com/_/mariadb 

##  Initializing a fresh instance
>When a container is started for the first time, a new database with the specified name will be created and initialized with the provided configuration variables. Furthermore, it will execute files with extensions .sh, .sql, .sql.gz, and .sql.xz that are found in /docker-entrypoint-initdb.d. Files will be executed in alphabetical order. .sh files without file execute permission are sourced rather than executed. You can easily populate your mariadb services by mounting a SQL dump into that directory and provide custom images with contributed data. SQL files will be imported by default to the database specified by the MARIADB_DATABASE / MYSQL_DATABASE variable.

I used this mechanism before with the local dev environment for some D7 sites at my previous employer and it worked well.

**Comment by olivereri** [comment]
Not having a ton of luck with the initialization of the DB through /docker-entrypoint-initdb.d.

```
FROM mariadb:10.5
ENV MARIADB_ROOT_PASSWORD="drupal8"
ENV MARIADB_DATABASE="drupal8"
ENV MARIADB_USER="drupal8"
ADD cms-prod-db-sanitized-latest.sql.gz /docker-entrypoint-initdb.d
```

```
mk8s@Tritium:~/docker/cms/cms-db$ docker run cms-db:0.0.414 -it bash
2021-09-29 18:21:50+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.5.12+maria~focal started.
2021-09-29 18:21:50+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
        command was: mysqld -it bash --verbose --help --log-bin-index=/tmp/tmp.qIedQ1TfQ8
        2021-09-29 18:21:50 0 [Warning] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some options may be missing from the help text
2021-09-29 18:21:50 0 [ERROR] mysqld: unknown option '-i'
```

**Comment by ndouglas** [comment]
You gotta do `docker run  -it bash cms-db:0.0.414` because it'll interpret anything after IMAGE:TAG as arguments to the entrypoint.  I don't think that'll fix the issue necessarily... that looks kind of like the volume is corrupted/incomplete.

**Comment by ndouglas** [comment]
You shouldn't need to do the docker-entrypoint-initdb.d thing inside the Dockerfile, though -- do something like `docker run -v $(pwd)/dump:/docker-entrypoint-initdb.d cms-db:0.0.414` and it should load it up as part of the startup process.

**Comment by olivereri** [comment]
Welp, I was running the command wrong. This works:
`docker run -it cms-db:0.0.414 bash`

> do something like docker run -v $(pwd)/dump:/docker-entrypoint-initdb.d cms-db:0.0.414 and it should load it up as part of the startup process.

But what if I'm looking to create a container image that contains the CMS DB already loaded? So I can pull that image as part of a K8s mainfest and deploy with ArgoCD

**Comment by ndouglas** [comment]
Sorry, was off getting my 🍑 handed to me by another issue of my own creation 😩 

>Welp, I was running the command wrong. This works:

🤦 yeah, I switched the arguments above, my bad.

>But what if I'm looking to create a container image that contains the CMS DB already loaded? So I can pull that image as part of a K8s mainfest and deploy with ArgoCD

I guess it depends on how ephemeral these environments are.  Loading the DB into the image will work but not for something dev/stg/prod-like.  It might be an option for local/CI though 🤔  

What I'm doing (haven't gotten it to work yet, though):

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mariadb
  namespace: cms-drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      initContainers:
        - name: init-files
          image: curlimages/curl:7.79.1
          command: ['/bin/bash', '-c']
          args:
            - 'cd /data; curl --remote-name https://dsva-vagov-prod-cms-backup-sanitized.s3-us-gov-west-1.amazonaws.com/database/cms-prod-db-sanitized-latest.sql.gz'
          volumeMounts:
            - mountPath: /data
              subPath: init-database
              name: init-database
      containers:
        - name: mariadb
          image: mariadb:10.5
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: drupal
            - name: MYSQL_USER
              value: drupal
            - name: MYSQL_PASSWORD
              value: drupal
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: 'yes'
          volumeMounts:
            - mountPath: /var/lib/mysql/
              name: database
              subPath: mysql
            - mountPath: /docker-entrypoint-initdb.d
              name: init-database
              subPath: init-database
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: init-database
          persistentVolumeClaim:
            claimName: mariadb-init-pvc
```

So the idea is that the initContainer pulls the DB dump, and then it'll get loaded by the DB container.

I guess the approach just depends on what you're trying to accomplish.  Copying it into the container should definitely work, and so far mine isn't, so IDK 😛
